# FlashStat Configuration
# 🏮 The Transparency Layer for Unichain

[rpc]
# ws_url = "wss://unichain-sepolia.api.onfinality.io/public-ws"
ws_url = "wss://boldest-dark-liquid.unichain-sepolia.quiknode.pro/c2eef6b727dc39db498c7b2e6659a1f5f2b8f4bd"

# http_url = "https://sepolia.unichain.org"
http_url = "https://boldest-dark-liquid.unichain-sepolia.quiknode.pro/c2eef6b727dc39db498c7b2e6659a1f5f2b8f4bd"

[storage]
db_path = "./data/flashstat_db"

[tee]
# Placeholder for the Unichain sequencer TEE address
sequencer_address = "0x4ab3387810ef500bfe05a49dc53a44c222cbab3e"
attestation_enabled = false
expected_mrenclave = "0000000000000000000000000000000000000000000000000000000000000000"

[guardian]
# Private key for the guardian wallet (use environment variables in production!)
# FLASHSTAT__GUARDIAN__PRIVATE_KEY
private_key = "5efc4b7414983a31e0cb2a45c265043a2a6bfd8b82808c5b8f59ddfff04db34c"
# Address of the Unichain SlashingManager contract
slashing_contract = "0x192136979A03A89f3A818a7a72E762E4A7D0D279"
